version: "3.8"

services:
  # Database
  database:
    image: mysql:8.0.25
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}:3306

  # Laravel Application
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    working_dir: /var/www/backend
    depends_on:
      - "database"

  # react Application

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"

  # Web Server
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
